import type { CollectionConfig } from 'payload'

import { slugify } from '@/lib/slugify'

export const VariantTypes: CollectionConfig = {
  slug: 'variant-types',
  admin: {
    useAsTitle: 'label',
    defaultColumns: ['label', 'name', '_status'],
    group: 'Catalog',
    description:
      'Catalog definitions for attributes and variant options (e.g. Color, Size). Assign values under Variant Option Values.',
  },
  access: {
    read: () => true,
  },
  hooks: {
    beforeChange: [
      ({ data, originalDoc }) => {
        if (!data) return data

        const label = data.label ?? originalDoc?.label
        const name = data.name

        if (typeof label === 'string' && label.trim() !== '') {
          const nameIsEmpty = typeof name !== 'string' || name.trim() === ''
          const nameWasAutoGenerated =
            typeof originalDoc?.label === 'string' &&
            typeof originalDoc?.name === 'string' &&
            originalDoc.name === slugify(originalDoc.label)

          if (nameIsEmpty || nameWasAutoGenerated) {
            data.name = slugify(label)
          }
        }

        return data
      },
    ],
  },
  fields: [
    {
      name: 'label',
      type: 'text',
      required: true,
      admin: {
        description: 'Display name shown in the admin and storefront, e.g. Color or Size.',
      },
    },
    {
      name: 'name',
      type: 'text',
      required: true,
      unique: true,
      admin: {
        position: 'sidebar',
        description: 'Machine key auto-generated from the label. Edit to override.',
      },
    },
    {
      name: 'isPrimaryVisualType',
      type: 'checkbox',
      defaultValue: false,
      label: 'Primary visual type',
      admin: {
        position: 'sidebar',
        description:
          'When enabled, the storefront gallery follows the selected value of this type (e.g. Color). Upload images on each product under Variant Visual Galleries.',
      },
    },
    {
      name: 'optionValues',
      type: 'join',
      collection: 'variant-option-values',
      on: 'variantType',
      admin: {
        description:
          'Allowed values for this type. Use + to add values here or under Catalog → Variant Option Values.',
        allowCreate: true,
        defaultColumns: ['value', '_status'],
      },
    },
  ],
}
