import type { CollectionConfig } from 'payload'

import { slugify } from '@/lib/slugify'

export const VariantTypes: CollectionConfig = {
  slug: 'variant-types',
  admin: {
    useAsTitle: 'label',
    defaultColumns: ['label', 'name', '_status'],
    group: 'Catalog',
  },
  access: {
    read: () => true,
  },
  hooks: {
    beforeChange: [
      ({ data, originalDoc }) => {
        if (!data) return data

        const label = data.label ?? originalDoc?.label
        const name = data.name

        if (typeof label === 'string' && label.trim() !== '') {
          const nameIsEmpty = typeof name !== 'string' || name.trim() === ''
          const nameWasAutoGenerated =
            typeof originalDoc?.label === 'string' &&
            typeof originalDoc?.name === 'string' &&
            originalDoc.name === slugify(originalDoc.label)

          if (nameIsEmpty || nameWasAutoGenerated) {
            data.name = slugify(label)
          }
        }

        return data
      },
    ],
  },
  fields: [
    {
      name: 'label',
      type: 'text',
      required: true,
      admin: {
        description: 'Display name shown in the admin and storefront, e.g. Color.',
      },
    },
    {
      name: 'name',
      type: 'text',
      required: true,
      unique: true,
      admin: {
        position: 'sidebar',
        description: 'Machine key auto-generated from the label. Edit to override.',
      },
    },
    {
      name: 'options',
      type: 'array',
      labels: {
        singular: 'Option',
        plural: 'Options',
      },
      admin: {
        description: 'Allowed values for this variant type, e.g. Red, Blue, Black.',
        initCollapsed: false,
      },
      fields: [
        {
          name: 'value',
          type: 'text',
          required: true,
        },
      ],
    },
  ],
}
