import type { CollectionBeforeChangeHook, CollectionConfig, Config, Field, Plugin } from 'payload'

import { formatSlug } from '@/lib/formatSlug'
import { slugify } from '@/lib/slugify'

function hasSlugField(fields: CollectionConfig['fields']): boolean {
  return fields?.some((field) => isSlugField(field)) ?? false
}

function isSlugField(field: Field): field is Field & { name: 'slug'; type: 'text' } {
  return 'name' in field && field.name === 'slug' && field.type === 'text'
}

function getSourceField(collection: CollectionConfig): string {
  const useAsTitle = collection.admin?.useAsTitle
  return typeof useAsTitle === 'string' ? useAsTitle : 'title'
}

function createAutoSlugHook(sourceField: string): CollectionBeforeChangeHook {
  return ({ data, originalDoc, operation }) => {
    if (!data) {
      return data
    }

    const source = data[sourceField] ?? originalDoc?.[sourceField]
    if (typeof source !== 'string' || source.trim() === '') {
      return data
    }

    const slug = data.slug
    const previousSlug = originalDoc?.slug
    const previousSource = originalDoc?.[sourceField]

    const slugIsEmpty = typeof slug !== 'string' || slug.trim() === ''
    const slugWasAutoGenerated =
      operation === 'update' &&
      typeof previousSource === 'string' &&
      typeof previousSlug === 'string' &&
      previousSlug === slugify(previousSource)

    if (slugIsEmpty || slugWasAutoGenerated) {
      data.slug = slugify(source)
    }

    return data
  }
}

function applySlugFieldDefaults(fields: CollectionConfig['fields'], sourceField: string) {
  return fields?.map((field) => {
    if (!isSlugField(field)) {
      return field
    }

    return {
      ...field,
      admin: {
        ...field.admin,
        position: field.admin?.position ?? 'sidebar',
        description:
          field.admin?.description ??
          `Auto-generated from ${sourceField} when empty. Edit to override.`,
      },
      hooks: {
        ...field.hooks,
        beforeValidate: [...(field.hooks?.beforeValidate ?? []), formatSlug(sourceField)],
      },
    }
  })
}

function enableAutoSlug(collection: CollectionConfig): CollectionConfig {
  const sourceField = getSourceField(collection)
  const hook = createAutoSlugHook(sourceField)

  return {
    ...collection,
    fields: applySlugFieldDefaults(collection.fields, sourceField),
    hooks: {
      ...collection.hooks,
      beforeChange: [...(collection.hooks?.beforeChange ?? []), hook],
    },
  }
}

export const autoSlugPlugin =
  (): Plugin =>
  (config: Config): Config => ({
    ...config,
    collections: (config.collections ?? []).map((collection) => {
      if (collection.auth || collection.upload || !hasSlugField(collection.fields)) {
        return collection
      }

      return enableAutoSlug(collection)
    }),
  })
